### ISSUE TITLE
[Refacter]: 리뷰 & 게시판 기능 수정

### ISSUE THREAD

**Issue by jchyng** [Weiver-project/Weiver#10]
## Before😐
리뷰 작성 시 작품명 지정
잡담 작성 시 작품명 연결 기능 없음
공연 상세에서 해당 공연의 리뷰를 볼 수 없음

## After😎
공연 상세에서만 리뷰 작성 가능 = 해당 공연 아이디 연결
잡담 작성 시 작품명 연결 기능 생성
공연 상세에서 해당 공연의 리뷰를 볼 수 있음

**Comment by mini-boo** [comment]
Solution😎

뮤지컬 상세 정보 페이지 > 리뷰 X, 오로지 정보만 노출
