### ISSUE TITLE
[Feat]: 컨텐츠 삭제 로직 정하기

### ISSUE THREAD

**Issue by jchyng** [Weiver-project/Weiver#8]
## 📃To do List
- [ ] 게시글 삭제 시 관련된 데이터를 트리거로 삭제 vs 게시글만 삭제하고 나머지 데이터는 보존
- [ ] 데이터 삭제 시 몇일 동안 보관할 지
- [ ] 데이터 삭제 시 상태 필드를 추가할 지, 다른 방법을 사용할 지

**Comment by Dev-LJH** [comment]
게시글 삭제 시 관련된 데이터를 트리거로 삭제
게시글, 회원정보는 바로 삭제 되도록
